export { NexusBrowser, type BrowserVersion, type TargetInfo } from './browser/browser.ts';
export { findChromium, type LaunchOptions } from './browser/launcher.ts';
export { CdpClient, CdpSession, type SendOptions } from './cdp/client.ts';
export { WebSocketTransport, type Transport } from './cdp/transport.ts';
export { DomSnapshot, type DomNode, type NodeRef, type Rect } from './dom/snapshot.ts';
export { ElementHandle, type OptionSpec } from './element/element.ts';
export { expect, LocatorAssertions, PageAssertions } from './expect.ts';
export { Locator, type TimeoutOptions, type WaitForOptions } from './locator/locator.ts';
export { NexusPage, type BindingSource, type DialogPolicy, type DialogRecord, type GotoOptions, type PageEventMap, type ScreenshotOptions, type WaitUntil } from './page/page.ts';
export * from './errors.ts';
export { BrowserContext } from './browser/context.ts';
export { NetworkTracker, type NetworkIdleOptions } from './page/network.ts';
export { bindParams, parseTask, type Step, type TargetSpec, type Task } from './task/schema.ts';
export { renderReport } from './task/report.ts';
export { loadTask, runTask, type RunTaskOptions, type ScreenshotPolicy, type StepResult, type TaskResult } from './task/runner.ts';
export { Recorder, type RawStep, type RecorderOptions } from './recorder/recorder.ts';
export { looksStable, targetFor } from './recorder/targets.ts';
export { pageOutline, type OutlineOptions } from './heal/outline.ts';
export { deterministicRepair, isRepairable, rejectProposal, similarity, type RepairContext, type RepairProposal, type TargetAdvisor } from './heal/repair.ts';
export { ClaudeAdvisor, type ClaudeAdvisorOptions } from './ai/advisor.ts';
export { draftTask, type DraftEvent, type DraftOptions, type DraftResult } from './ai/drafter.ts';
export { createClaudeClient, DEFAULT_MODEL, type ModelClient } from './ai/model.ts';
export { StepExecutor, type HealOptions, type StepRepair } from './task/runner.ts';
export { parseTarget, replaceRawTarget, stepTarget, withTarget } from './task/schema.ts';
export { createModelClient, createOpenAICompatibleClient } from './ai/openai-compatible.ts';
export { profileDir, profilesRoot } from './browser/profile.ts';
